import { prisma } from "@/lib/prisma";
import { generateCode } from "@/lib/codegen";
import { logAudit } from "@/lib/audit";
import { notifyStatusChange } from "@/lib/notify";

// Purchase Request otomatis dibuat ketika stok tersedia (stock - reserved) suatu material
// sudah memenuhi/di bawah ambang minimum, dan belum ada PR aktif (PENDING/APPROVED) untuk material tsb.
export async function autoCreatePurchaseRequestIfNeeded(materialId: string) {
  const material = await prisma.material.findUnique({ where: { id: materialId } });
  if (!material || material.isDeleted) return null;

  const available = Number(material.stockQty) - Number(material.reservedQty);
  const minStock = Number(material.minStockQty);
  if (minStock <= 0 || available > minStock) return null;

  const existingOpenRequest = await prisma.purchaseRequest.findFirst({
    where: { materialId, isDeleted: false, status: { in: ["PENDING", "APPROVED"] } },
  });
  if (existingOpenRequest) return null;

  const requester = await prisma.user.findFirst({
    where: { isDeleted: false, isActive: true, role: { in: ["PURCHASING", "OWNER"] } },
    orderBy: { role: "asc" }, // PURCHASING < ... alfabetis, tapi pastikan fallback ke OWNER tetap ada
  });
  if (!requester) return null;

  // Restock target: kembalikan ke 2x stok minimum, minimal selisih kekurangan.
  const targetQty = Math.max(minStock * 2 - available, minStock);
  const code = await generateCode("purchaseRequest");

  const pr = await prisma.purchaseRequest.create({
    data: {
      code,
      materialId,
      qty: targetQty,
      supplierId: material.supplierId,
      estimatedCost: targetQty * Number(material.pricePerUnit),
      requestedById: requester.id,
      status: "PENDING",
      autoGenerated: true,
      note: `Dibuat otomatis: stok tersedia (${available}) sudah mencapai/di bawah minimum (${minStock}).`,
    },
  });

  await logAudit({
    userId: null,
    module: "purchasing",
    action: "CREATE",
    referenceCode: pr.code,
    newValue: { autoGenerated: true, materialId, qty: targetQty },
  });
  await notifyStatusChange({
    moduleKeys: ["purchase-request"],
    module: "purchase-request",
    type: "APPROVAL",
    href: "/purchase-request",
    referenceCode: pr.code,
    title: "Purchase Request otomatis (stok minimum)",
    message: `Stok ${material.name} sudah di bawah minimum. Sistem membuat ${pr.code} otomatis, silakan review & approve.`,
  });

  return pr;
}

// Safety-net: scan semua material aktif yang stoknya sudah di bawah minimum lalu buat PR
// otomatis bila belum ada. Dipanggil ringan di halaman Purchase Request / Material & Stok.
export async function autoCreatePurchaseRequestsForAllLowStock() {
  const candidates = await prisma.material.findMany({
    where: { isDeleted: false, minStockQty: { gt: 0 } },
    select: { id: true },
  });
  for (const material of candidates) {
    await autoCreatePurchaseRequestIfNeeded(material.id).catch(() => null);
  }
}
