-- CreateEnum
CREATE TYPE "DeliveryStage" AS ENUM ('READY', 'IN_DELIVERY', 'PENDING', 'DELIVERED');

-- AlterEnum
ALTER TYPE "WorkOrderStage" ADD VALUE 'PACKING';

-- AlterTable
ALTER TABLE "CompanySettings" ADD COLUMN     "designPrefix" TEXT NOT NULL DEFAULT 'DSG',
ADD COLUMN     "productCategoryPrefix" TEXT NOT NULL DEFAULT 'CAT';

-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "categoryId" TEXT;

-- AlterTable
ALTER TABLE "PurchaseRequest" ADD COLUMN     "autoGenerated" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "Quotation" ADD COLUMN     "requestedDeliveryDate" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "SalesOrder" ADD COLUMN     "requestedDeliveryDate" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "WorkOrder" ADD COLUMN     "isInRevision" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "prepressDesignUploadedAt" TIMESTAMP(3),
ADD COLUMN     "prepressDesignUrl" TEXT,
ADD COLUMN     "revisionCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "revisionNote" TEXT;

-- CreateTable
CREATE TABLE "ProductCategory" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "isDeleted" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ProductCategory_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DeliveryOrder" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "salesOrderId" TEXT NOT NULL,
    "stage" "DeliveryStage" NOT NULL DEFAULT 'READY',
    "note" TEXT,
    "deliveredAt" TIMESTAMP(3),
    "isDeleted" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DeliveryOrder_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DesignMaster" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "driveUrl" TEXT NOT NULL,
    "productId" TEXT,
    "note" TEXT,
    "isDeleted" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DesignMaster_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ProductCategory_code_key" ON "ProductCategory"("code");

-- CreateIndex
CREATE INDEX "ProductCategory_name_idx" ON "ProductCategory"("name");

-- CreateIndex
CREATE UNIQUE INDEX "DeliveryOrder_code_key" ON "DeliveryOrder"("code");

-- CreateIndex
CREATE UNIQUE INDEX "DeliveryOrder_salesOrderId_key" ON "DeliveryOrder"("salesOrderId");

-- CreateIndex
CREATE INDEX "DeliveryOrder_stage_idx" ON "DeliveryOrder"("stage");

-- CreateIndex
CREATE UNIQUE INDEX "DesignMaster_code_key" ON "DesignMaster"("code");

-- CreateIndex
CREATE INDEX "DesignMaster_name_idx" ON "DesignMaster"("name");

-- AddForeignKey
ALTER TABLE "Product" ADD CONSTRAINT "Product_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "ProductCategory"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DeliveryOrder" ADD CONSTRAINT "DeliveryOrder_salesOrderId_fkey" FOREIGN KEY ("salesOrderId") REFERENCES "SalesOrder"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DesignMaster" ADD CONSTRAINT "DesignMaster_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE SET NULL ON UPDATE CASCADE;
